package com.qixi.db.entity;

public class AreaInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areainfo.id
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areainfo.regionId
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areainfo.name
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areainfo.remark
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areainfo.ext1
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    private Integer ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areainfo.ext2
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    private String ext2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areainfo.id
     *
     * @return the value of areainfo.id
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areainfo.id
     *
     * @param id the value for areainfo.id
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areainfo.regionId
     *
     * @return the value of areainfo.regionId
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areainfo.regionId
     *
     * @param regionId the value for areainfo.regionId
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areainfo.name
     *
     * @return the value of areainfo.name
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areainfo.name
     *
     * @param name the value for areainfo.name
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areainfo.remark
     *
     * @return the value of areainfo.remark
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areainfo.remark
     *
     * @param remark the value for areainfo.remark
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areainfo.ext1
     *
     * @return the value of areainfo.ext1
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    public Integer getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areainfo.ext1
     *
     * @param ext1 the value for areainfo.ext1
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    public void setExt1(Integer ext1) {
        this.ext1 = ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areainfo.ext2
     *
     * @return the value of areainfo.ext2
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areainfo.ext2
     *
     * @param ext2 the value for areainfo.ext2
     *
     * @mbggenerated Wed Feb 26 00:22:44 CST 2014
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }
}