package com.qixi.db.entity;

import java.util.Date;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.uid
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.readCount
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private Integer readCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.status
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.createDate
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.updateDate
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.uid
     *
     * @return the value of blog.uid
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.uid
     *
     * @param uid the value for blog.uid
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.readCount
     *
     * @return the value of blog.readCount
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.readCount
     *
     * @param readCount the value for blog.readCount
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.status
     *
     * @return the value of blog.status
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.status
     *
     * @param status the value for blog.status
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.createDate
     *
     * @return the value of blog.createDate
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.createDate
     *
     * @param createDate the value for blog.createDate
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.updateDate
     *
     * @return the value of blog.updateDate
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.updateDate
     *
     * @param updateDate the value for blog.updateDate
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}