package com.qixi.db.entity;

import java.util.Date;

public class BlogComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.id
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.uid
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.blogId
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private Integer blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.status
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.createDate
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.updateDate
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcomment.content
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.id
     *
     * @return the value of blogcomment.id
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.id
     *
     * @param id the value for blogcomment.id
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.uid
     *
     * @return the value of blogcomment.uid
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.uid
     *
     * @param uid the value for blogcomment.uid
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.blogId
     *
     * @return the value of blogcomment.blogId
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.blogId
     *
     * @param blogId the value for blogcomment.blogId
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.status
     *
     * @return the value of blogcomment.status
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.status
     *
     * @param status the value for blogcomment.status
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.createDate
     *
     * @return the value of blogcomment.createDate
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.createDate
     *
     * @param createDate the value for blogcomment.createDate
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.updateDate
     *
     * @return the value of blogcomment.updateDate
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.updateDate
     *
     * @param updateDate the value for blogcomment.updateDate
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcomment.content
     *
     * @return the value of blogcomment.content
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcomment.content
     *
     * @param content the value for blogcomment.content
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}