package com.qixi.db.entity;

public class qq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qq.id
     *
     * @mbggenerated Sat Apr 25 11:46:11 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qq.qq
     *
     * @mbggenerated Sat Apr 25 11:46:11 CST 2015
     */
    private String qq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq.id
     *
     * @return the value of qq.id
     *
     * @mbggenerated Sat Apr 25 11:46:11 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq.id
     *
     * @param id the value for qq.id
     *
     * @mbggenerated Sat Apr 25 11:46:11 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq.qq
     *
     * @return the value of qq.qq
     *
     * @mbggenerated Sat Apr 25 11:46:11 CST 2015
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq.qq
     *
     * @param qq the value for qq.qq
     *
     * @mbggenerated Sat Apr 25 11:46:11 CST 2015
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }
}