package com.qixi.db.entity;

public class qq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qq.id
     *
     * @mbggenerated Tue Jun 23 21:28:20 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qq.qq
     *
     * @mbggenerated Tue Jun 23 21:28:20 CST 2015
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qq.flag
     *
     * @mbggenerated Tue Jun 23 21:28:20 CST 2015
     */
    private Boolean flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq.id
     *
     * @return the value of qq.id
     *
     * @mbggenerated Tue Jun 23 21:28:20 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq.id
     *
     * @param id the value for qq.id
     *
     * @mbggenerated Tue Jun 23 21:28:20 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq.qq
     *
     * @return the value of qq.qq
     *
     * @mbggenerated Tue Jun 23 21:28:20 CST 2015
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq.qq
     *
     * @param qq the value for qq.qq
     *
     * @mbggenerated Tue Jun 23 21:28:20 CST 2015
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qq.flag
     *
     * @return the value of qq.flag
     *
     * @mbggenerated Tue Jun 23 21:28:20 CST 2015
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qq.flag
     *
     * @param flag the value for qq.flag
     *
     * @mbggenerated Tue Jun 23 21:28:20 CST 2015
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }
}