package com.qixi.db.entity;

import java.util.Date;

public class UserBasic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.uid
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.uuid
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.regEmail
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private String regEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.nickName
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.gender
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.randomKey
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private String randomKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.password
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.avatar
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.birthday
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.signature
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.areaId
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.state
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.signUpTime
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private Date signUpTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.lastLoginTime
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.regIp
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private String regIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.lastIp
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private String lastIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.lastLocation
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private String lastLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.ext1
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private Integer ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasic.ext2
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    private String ext2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.uid
     *
     * @return the value of userbasic.uid
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.uid
     *
     * @param uid the value for userbasic.uid
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.uuid
     *
     * @return the value of userbasic.uuid
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.uuid
     *
     * @param uuid the value for userbasic.uuid
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.regEmail
     *
     * @return the value of userbasic.regEmail
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public String getRegEmail() {
        return regEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.regEmail
     *
     * @param regEmail the value for userbasic.regEmail
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setRegEmail(String regEmail) {
        this.regEmail = regEmail == null ? null : regEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.nickName
     *
     * @return the value of userbasic.nickName
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.nickName
     *
     * @param nickName the value for userbasic.nickName
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.gender
     *
     * @return the value of userbasic.gender
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.gender
     *
     * @param gender the value for userbasic.gender
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.randomKey
     *
     * @return the value of userbasic.randomKey
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public String getRandomKey() {
        return randomKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.randomKey
     *
     * @param randomKey the value for userbasic.randomKey
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setRandomKey(String randomKey) {
        this.randomKey = randomKey == null ? null : randomKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.password
     *
     * @return the value of userbasic.password
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.password
     *
     * @param password the value for userbasic.password
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.avatar
     *
     * @return the value of userbasic.avatar
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.avatar
     *
     * @param avatar the value for userbasic.avatar
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.birthday
     *
     * @return the value of userbasic.birthday
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.birthday
     *
     * @param birthday the value for userbasic.birthday
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.signature
     *
     * @return the value of userbasic.signature
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.signature
     *
     * @param signature the value for userbasic.signature
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.areaId
     *
     * @return the value of userbasic.areaId
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.areaId
     *
     * @param areaId the value for userbasic.areaId
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.state
     *
     * @return the value of userbasic.state
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.state
     *
     * @param state the value for userbasic.state
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.signUpTime
     *
     * @return the value of userbasic.signUpTime
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public Date getSignUpTime() {
        return signUpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.signUpTime
     *
     * @param signUpTime the value for userbasic.signUpTime
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setSignUpTime(Date signUpTime) {
        this.signUpTime = signUpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.lastLoginTime
     *
     * @return the value of userbasic.lastLoginTime
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.lastLoginTime
     *
     * @param lastLoginTime the value for userbasic.lastLoginTime
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.regIp
     *
     * @return the value of userbasic.regIp
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public String getRegIp() {
        return regIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.regIp
     *
     * @param regIp the value for userbasic.regIp
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setRegIp(String regIp) {
        this.regIp = regIp == null ? null : regIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.lastIp
     *
     * @return the value of userbasic.lastIp
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.lastIp
     *
     * @param lastIp the value for userbasic.lastIp
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.lastLocation
     *
     * @return the value of userbasic.lastLocation
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public String getLastLocation() {
        return lastLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.lastLocation
     *
     * @param lastLocation the value for userbasic.lastLocation
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setLastLocation(String lastLocation) {
        this.lastLocation = lastLocation == null ? null : lastLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.ext1
     *
     * @return the value of userbasic.ext1
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public Integer getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.ext1
     *
     * @param ext1 the value for userbasic.ext1
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setExt1(Integer ext1) {
        this.ext1 = ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasic.ext2
     *
     * @return the value of userbasic.ext2
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasic.ext2
     *
     * @param ext2 the value for userbasic.ext2
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }
}