package com.qixi.db.entity;

import java.util.Date;

public class Vote {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.id
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.uid
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.title
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.remark
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.endDate
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.maxItem
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    private Short maxItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.state
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.createDate
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.updateDate
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.id
     *
     * @return the value of vote.id
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.id
     *
     * @param id the value for vote.id
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.uid
     *
     * @return the value of vote.uid
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.uid
     *
     * @param uid the value for vote.uid
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.title
     *
     * @return the value of vote.title
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.title
     *
     * @param title the value for vote.title
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.remark
     *
     * @return the value of vote.remark
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.remark
     *
     * @param remark the value for vote.remark
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.endDate
     *
     * @return the value of vote.endDate
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.endDate
     *
     * @param endDate the value for vote.endDate
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.maxItem
     *
     * @return the value of vote.maxItem
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public Short getMaxItem() {
        return maxItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.maxItem
     *
     * @param maxItem the value for vote.maxItem
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public void setMaxItem(Short maxItem) {
        this.maxItem = maxItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.state
     *
     * @return the value of vote.state
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.state
     *
     * @param state the value for vote.state
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.createDate
     *
     * @return the value of vote.createDate
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.createDate
     *
     * @param createDate the value for vote.createDate
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.updateDate
     *
     * @return the value of vote.updateDate
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.updateDate
     *
     * @param updateDate the value for vote.updateDate
     *
     * @mbggenerated Sun Jul 13 17:35:52 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}