package com.qixi.db.entity;

import java.util.Date;

public class VoteComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votecomment.id
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votecomment.voteId
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    private Integer voteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votecomment.uid
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votecomment.comment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votecomment.state
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votecomment.createTime
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votecomment.updateTime
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votecomment.id
     *
     * @return the value of votecomment.id
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votecomment.id
     *
     * @param id the value for votecomment.id
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votecomment.voteId
     *
     * @return the value of votecomment.voteId
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public Integer getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votecomment.voteId
     *
     * @param voteId the value for votecomment.voteId
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public void setVoteId(Integer voteId) {
        this.voteId = voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votecomment.uid
     *
     * @return the value of votecomment.uid
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votecomment.uid
     *
     * @param uid the value for votecomment.uid
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votecomment.comment
     *
     * @return the value of votecomment.comment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votecomment.comment
     *
     * @param comment the value for votecomment.comment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votecomment.state
     *
     * @return the value of votecomment.state
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votecomment.state
     *
     * @param state the value for votecomment.state
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votecomment.createTime
     *
     * @return the value of votecomment.createTime
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votecomment.createTime
     *
     * @param createTime the value for votecomment.createTime
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votecomment.updateTime
     *
     * @return the value of votecomment.updateTime
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votecomment.updateTime
     *
     * @param updateTime the value for votecomment.updateTime
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}