package com.qixi.db.entity;

import java.util.Date;

public class VoteSelect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteselect.id
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteselect.voteId
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    private Integer voteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteselect.itemId
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteselect.uid
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteselect.createDate
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteselect.id
     *
     * @return the value of voteselect.id
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteselect.id
     *
     * @param id the value for voteselect.id
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteselect.voteId
     *
     * @return the value of voteselect.voteId
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public Integer getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteselect.voteId
     *
     * @param voteId the value for voteselect.voteId
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public void setVoteId(Integer voteId) {
        this.voteId = voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteselect.itemId
     *
     * @return the value of voteselect.itemId
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteselect.itemId
     *
     * @param itemId the value for voteselect.itemId
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteselect.uid
     *
     * @return the value of voteselect.uid
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteselect.uid
     *
     * @param uid the value for voteselect.uid
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteselect.createDate
     *
     * @return the value of voteselect.createDate
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteselect.createDate
     *
     * @param createDate the value for voteselect.createDate
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}