package com.qixi.db.mapper;

import com.qixi.db.entity.BlogComment;
import com.qixi.db.entity.BlogCommentExample;
import com.qixi.db.entity.extend.BlogCommentExtend;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface BlogCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    int countByExample(BlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    int deleteByExample(BlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    int insert(BlogComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    int insertSelective(BlogComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    List<BlogComment> selectByExampleWithBLOBs(BlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    List<BlogComment> selectByExample(BlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") BlogComment record, @Param("example") BlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") BlogComment record, @Param("example") BlogCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcomment
     *
     * @mbggenerated Mon Mar 02 23:28:20 CST 2015
     */
    int updateByExample(@Param("record") BlogComment record, @Param("example") BlogCommentExample example);

    List<BlogCommentExtend> getBlogCommentExtend(Map<String, Object> parameterMap);
}