package com.qixi.db.mapper;

import com.qixi.db.entity.UserBasic;
import com.qixi.db.entity.UserBasicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBasicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbasic
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    int countByExample(UserBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbasic
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    int deleteByExample(UserBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbasic
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbasic
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    int insert(UserBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbasic
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    int insertSelective(UserBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbasic
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    List<UserBasic> selectByExample(UserBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbasic
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    UserBasic selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbasic
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    int updateByExampleSelective(@Param("record") UserBasic record, @Param("example") UserBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbasic
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    int updateByExample(@Param("record") UserBasic record, @Param("example") UserBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbasic
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    int updateByPrimaryKeySelective(UserBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbasic
     *
     * @mbggenerated Wed Feb 12 00:28:07 CST 2014
     */
    int updateByPrimaryKey(UserBasic record);
}