package com.qixi.db.mapper;

import com.qixi.db.entity.VoteSelect;
import com.qixi.db.entity.VoteSelectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteSelectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteselect
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int countByExample(VoteSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteselect
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int deleteByExample(VoteSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteselect
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteselect
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int insert(VoteSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteselect
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int insertSelective(VoteSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteselect
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    List<VoteSelect> selectByExample(VoteSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteselect
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    VoteSelect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteselect
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int updateByExampleSelective(@Param("record") VoteSelect record, @Param("example") VoteSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteselect
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int updateByExample(@Param("record") VoteSelect record, @Param("example") VoteSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteselect
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int updateByPrimaryKeySelective(VoteSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteselect
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int updateByPrimaryKey(VoteSelect record);
}