package com.qixi.db.mapper;

import com.qixi.db.entity.VoteItem;
import com.qixi.db.entity.VoteItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int countByExample(VoteItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int deleteByExample(VoteItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int insert(VoteItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int insertSelective(VoteItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    List<VoteItem> selectByExample(VoteItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    VoteItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int updateByExampleSelective(@Param("record") VoteItem record, @Param("example") VoteItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int updateByExample(@Param("record") VoteItem record, @Param("example") VoteItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int updateByPrimaryKeySelective(VoteItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int updateByPrimaryKey(VoteItem record);
}