package com.qixi.db.mapper;

import com.qixi.db.entity.VoteComment;
import com.qixi.db.entity.VoteCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votecomment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int countByExample(VoteCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votecomment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int deleteByExample(VoteCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votecomment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votecomment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int insert(VoteComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votecomment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int insertSelective(VoteComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votecomment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    List<VoteComment> selectByExample(VoteCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votecomment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    VoteComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votecomment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int updateByExampleSelective(@Param("record") VoteComment record, @Param("example") VoteCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votecomment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int updateByExample(@Param("record") VoteComment record, @Param("example") VoteCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votecomment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int updateByPrimaryKeySelective(VoteComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votecomment
     *
     * @mbggenerated Mon Jul 07 22:03:04 CST 2014
     */
    int updateByPrimaryKey(VoteComment record);
}